### ISSUE TITLE
Feature request -- Timer start trigger

### ISSUE THREAD

**Issue by lynaevm** [Insane-96/In-Game-Timer#1]
Hello! I would love to use this in my upcoming speedrun release but teams will need a little bit of team to get in a team and set up before the timer should start -- is it possible to add a configurable "start trigger" that can be set off by an action?

**Comment by Insane96** [comment]
Would a command be good?
`/igt:start`

**Comment by Insane96** [comment]
Closed via https://github.com/Insane-96/In-Game-Timer/commit/7969ad4eb51eb376dcc9233a5b05fb348a811e68
